[build-system]
requires = [
  "meson>=0.62.2",
  "meson-python>=0.7.0"
]
build-backend = "mesonpy"

[tool.cibuildwheel]
build-verbosity = 3
before-all = "bash {project}/cibw_before_all.sh"
manylinux-x86_64-image = "manylinux_2_24"
manylinux-i686-image = "manylinux_2_24"
manylinux-aarch64-image = "manylinux_2_24"
manylinux-ppc64le-image = "manylinux_2_24"
manylinux-s390x-image = "manylinux_2_24"
manylinux-pypy_x86_64-image = "manylinux_2_24"
manylinux-pypy_i686-image = "manylinux_2_24"
manylinux-pypy_aarch64-image = "manylinux_2_24"
skip = "pp*"

[tool.cibuildwheel.windows]
environment = { CMAKE_PREFIX_PATH="C:\\rizin" }
archs = ["AMD64"]

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64", "ppc64le", "s390x"]

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64", "universal2"]

[project]
name = "rz-bindings"
dynamic = [
  'version',
]
requires-python = ">=3.8"
readme = "README.md"
