name: build
on:
  push:
    branches:
      - dev
      - stable
      - 'ci-*'
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      external_call:
        description: 'To distinguish workflow_call from regular push'
        type: boolean
        required: false
        default: true
      rizin_ref:
        required: false
        type: string
        default: 'dev'

jobs:
  pypa-wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]

    steps:
    - name: Install SWIG with Homebrew
      if: matrix.os == 'macos-14' && matrix.enabled
      run: brew install swig

    - name: Checkout rz-bindgen
      uses: actions/checkout@v6

    # runned only from workflow_call
    - name: Checkout rizin
      if: ${{ inputs.external_call }}
      uses: actions/checkout@v6
      with:
        repository: rizinorg/rizin
        path: rizin
        ref: ${{ inputs.rizin_ref }}

    - name: Checkout rizin (stable)
      if: ${{ !inputs.external_call && ((github.ref_name == 'stable') || (github.base_ref == 'stable')) }}
      uses: actions/checkout@v6
      with:
        repository: rizinorg/rizin
        path: rizin
        ref: stable

    - name: Checkout rizin (dev)
      if: ${{ !inputs.external_call && ((github.ref_name != 'stable') && (github.base_ref != 'stable')) }}
      uses: actions/checkout@v6
      with:
        repository: rizinorg/rizin
        path: rizin
        ref: dev

    - name: Build rz-bindgen
      uses: pypa/cibuildwheel@v4.1.0

    - name: Upload sdist
      uses: actions/upload-artifact@v7
      with:
        name: sdist-${{ matrix.os }}
        path: dist/*.tar.gz

    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheels-${{ matrix.os }}
        path: wheelhouse/*.whl

  ubuntu-default-llvm:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout rz-bindgen
      uses: actions/checkout@v6
      with:
        path: rz-bindgen

    # runned only from workflow_call
    - name: Checkout rizin
      if: ${{ inputs.external_call }}
      uses: actions/checkout@v6
      with:
        repository: rizinorg/rizin
        path: rizin
        ref: ${{ inputs.rizin_ref }}

    - name: Checkout rizin (stable)
      if: ${{ !inputs.external_call && ((github.ref_name == 'stable') || (github.base_ref == 'stable')) }}
      uses: actions/checkout@v6
      with:
        repository: rizinorg/rizin
        path: rizin
        ref: stable

    - name: Checkout rizin (dev)
      if: ${{ !inputs.external_call && ((github.ref_name != 'stable') && (github.base_ref != 'stable')) }}
      uses: actions/checkout@v6
      with:
        repository: rizinorg/rizin
        path: rizin
        ref: dev

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get --assume-yes install cmake swig pkg-config clang libclang-dev llvm wget unzip python3-wheel python3-setuptools build-essential python3-pip
        sudo pip3 install meson ninja

    - name: Install rizin
      run: |
        export PATH=$PATH:/usr/local/bin
        meson setup --prefix=/usr --buildtype=release build && ninja -C build && sudo ninja -C build install
      working-directory: rizin

    - name: Build rz-bindgen
      run: |
        meson setup --prefix=/usr -Dplugin=enabled build
        meson compile -C build
        sudo meson install -C build
      working-directory: rz-bindgen

    - name: Test python lang plugin
      run: rizin -qc "Ll" | grep "Python SWIG"

    - name: Run rz-test
      run: rz-test -L tests/
      working-directory: rz-bindgen
