name: build
on:
  push:
  workflow_dispatch:
  workflow_call:
    inputs:
      rizin_ref:
        required: false
        type: string
        default: 'dev'

jobs:
  pypa-wheels:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-12]

    steps:
    - name: Checkout rz-bindgen
      uses: actions/checkout@v3

    - name: Checkout rizin
      uses: actions/checkout@v3
      with:
        repository: rizinorg/rizin
        path: rizin
        ref: ${{ inputs.rizin_ref }}

    - name: Build rz-bindgen
      uses: pypa/cibuildwheel@v2.8.0

    - name: Upload sdist
      uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: dist/*.tar.gz

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: wheelhouse/*.whl
