name: lint
on:
  push:
    branches:
      - dev
      - stable
      - 'ci-*'
  pull_request:
jobs:
  licenses:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout rz-bindgen
      uses: actions/checkout@v6
    - name: REUSE compliance check
      uses: fsfe/reuse-action@v6

  python:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout rz-bindgen
      uses: actions/checkout@v6
    - name: Install tools
      run: |
        pip install mypy pyflakes pylint black
    - name: Run mypy
      run: |
        mypy --disable-error-code misc src/main.py
      if: ${{ always() }}
    - name: Run pyflakes
      run: |
        pyflakes src/*.py
      if: ${{ always() }}
    - name: Run pylint
      run: |
        pylint src/*.py
      if: ${{ always() }}
    - name: Run black
      run: |
        black --check --diff src/*.py src/clang/cindex.pyi
      if: ${{ always() }}

  codeql:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
    - name: Checkout rz-bindgen
      uses: actions/checkout@v6
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: python
    - name: Run CodeQL
      uses: github/codeql-action/analyze@v4
