name: linting
on: push
jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout rz-bindgen
      uses: actions/checkout@v3
    - name: REUSE compliance check
      uses: fsfe/reuse-action@v1

  python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout rz-bindgen
      uses: actions/checkout@v3
    - name: Install tools
      run: |
        pip install mypy pyflakes pylint black
    - name: Run mypy
      run: |
        mypy src/main.py
      if: ${{ always() }}
    - name: Run pyflakes
      run: |
        pyflakes src/*.py
      if: ${{ always() }}
    - name: Run pylint
      run: |
        pylint src/*.py
      if: ${{ always() }}
    - name: Run black
      run: |
        black --check --diff src/*.py src/clang/cindex.pyi
      if: ${{ always() }}

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Checkout rz-bindgen
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python
    - name: Run CodeQL
      uses: github/codeql-action/analyze@v2
