name: release-rz-bindgen
on:
  push:
    tags:
      - rizin-v*_*
  workflow_dispatch:

jobs:
  extract-rizin-version:
    runs-on: ubuntu-latest
    outputs:
      rizin_version: ${{ steps.extract_version.outputs.result }}
    steps:
      - id: extract_version
        run: echo "result=$(echo ${{ github.ref }} | cut -d'_' -f1 | cut -d'-' -f2-)" >> "$GITHUB_OUTPUT"

  run-bindgen:
    uses: ./.github/workflows/ci.yml
    needs: [extract-rizin-version]
    with:
      rizin_ref: ${{ needs.extract-rizin-version.outputs.rizin_version }}

  publish-pypi:
    name: Publish PyPi
    runs-on: ubuntu-latest
    needs: [run-bindgen]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: dist
    - name: Download sdist
      uses: actions/download-artifact@v3
      with:
        name: sdist
        path: dist
    - name: Publish wheels
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
